In [170]:
import pandas as pd
import re

df = pd.read_csv(r'C:\Users\clint\Desktop\September 10\Code\Data\Analytic\word_count\Combined_word_count.csv')
df_og=df
df

           Location  Total_word_count
0      AK_Anchorage          1.26e+06
1          AK_Homer          2.35e+05
2          AK_Kenai          4.17e+05
3         AK_Palmer          2.31e+05
4     AK_Petersburg          8.32e+04
...             ...               ...
2634     WY_Douglas          3.13e+05
2635     WY_Jackson          3.22e+05
2636      WY_Lander          1.55e+05
2637     WY_Laramie          4.23e+05
2638     WY_Rawlins          2.17e+05

[2639 rows x 2 columns]

In [171]:
import pandas as pd

# Load the CSV file
file_path = r"C:\Users\clint\Desktop\September 10\Code\Data\Raw\transposed_df.csv"
transposed_df = pd.read_csv(file_path)
transposed_df
transposed_df_sorted = transposed_df.sort_values(by='Words')
transposed_df_sorted
transposed_df_sorted.reset_index(drop=True, inplace=True)
transposed_df_sorted

,Words,access,allocate,allow,allowable,application,approve,approved,authorize,ban,...,require,required,reserve,restrict,review,rezoning,set aside,shall,special,up to
0,AK_Anchorage,742,43,325,61,1704,195,0,891,2,...,5353,0,214,52,1068,67,0,19147,788,0
1,AK_Homer,140,15,46,2,322,32,0,198,0,...,1001,0,52,9,140,3,0,3653,187,0
2,AK_Kenai,188,12,71,15,589,69,0,673,0,...,1287,0,33,4,174,7,0,5213,407,0
3,AK_Palmer,95,9,38,5,243,19,0,177,1,...,903,0,20,6,101,7,0,3716,213,0
4,AK_Petersburg,52,1,17,5,137,13,0,40,3,...,335,0,13,1,36,3,0,1289,48,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,WY_Douglas,156,2,69,2,928,40,0,286,0,...,1915,0,37,6,596,174,0,5521,258,0
2635,WY_Jackson,183,15,79,22,639,76,0,125,0,...,1605,0,40,16,387,0,0,4497,345,0
2636,WY_Lander,58,0,30,15,209,23,0,68,0,...,736,0,3,3,65,2,0,3707,72,0
2637,WY_Laramie,295,11,118,10,610,86,0,252,0,...,1866,0,33,16,353,27,0,7492,374,0
2638,WY_Rawlins,123,1,36,5,233,25,0,203,0,...,877,0,8,7,69,2,0,3876,190,0

In [172]:
# Assuming df and transposed_df_sorted are already defined
transposed_df_sorted['total_word_count'] = df['Total_word_count'].values
transposed_df_sorted

,Words,access,allocate,allow,allowable,application,approve,approved,authorize,ban,...,required,reserve,restrict,review,rezoning,set aside,shall,special,up to,total_word_count
0,AK_Anchorage,742,43,325,61,1704,195,0,891,2,...,0,214,52,1068,67,0,19147,788,0,1.26e+06
1,AK_Homer,140,15,46,2,322,32,0,198,0,...,0,52,9,140,3,0,3653,187,0,2.35e+05
2,AK_Kenai,188,12,71,15,589,69,0,673,0,...,0,33,4,174,7,0,5213,407,0,4.17e+05
3,AK_Palmer,95,9,38,5,243,19,0,177,1,...,0,20,6,101,7,0,3716,213,0,2.31e+05
4,AK_Petersburg,52,1,17,5,137,13,0,40,3,...,0,13,1,36,3,0,1289,48,0,8.32e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,WY_Douglas,156,2,69,2,928,40,0,286,0,...,0,37,6,596,174,0,5521,258,0,3.13e+05
2635,WY_Jackson,183,15,79,22,639,76,0,125,0,...,0,40,16,387,0,0,4497,345,0,3.22e+05
2636,WY_Lander,58,0,30,15,209,23,0,68,0,...,0,3,3,65,2,0,3707,72,0,1.55e+05
2637,WY_Laramie,295,11,118,10,610,86,0,252,0,...,0,33,16,353,27,0,7492,374,0,4.23e+05
2638,WY_Rawlins,123,1,36,5,233,25,0,203,0,...,0,8,7,69,2,0,3876,190,0,2.17e+05

In [173]:
transposed_df_sorted = transposed_df_sorted.set_index('Words')
transposed_df_sorted

,access,allocate,allow,allowable,application,approve,approved,authorize,ban,board,...,required,reserve,restrict,review,rezoning,set aside,shall,special,up to,total_word_count
Words,,,,,,,,,,,,,,,,,,,,,
AK_Anchorage,742,43,325,61,1704,195,0,891,2,1742,...,0,214,52,1068,67,0,19147,788,0,1.26e+06
AK_Homer,140,15,46,2,322,32,0,198,0,316,...,0,52,9,140,3,0,3653,187,0,2.35e+05
AK_Kenai,188,12,71,15,589,69,0,673,0,868,...,0,33,4,174,7,0,5213,407,0,4.17e+05
AK_Palmer,95,9,38,5,243,19,0,177,1,214,...,0,20,6,101,7,0,3716,213,0,2.31e+05
AK_Petersburg,52,1,17,5,137,13,0,40,3,200,...,0,13,1,36,3,0,1289,48,0,8.32e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WY_Douglas,156,2,69,2,928,40,0,286,0,127,...,0,37,6,596,174,0,5521,258,0,3.13e+05
WY_Jackson,183,15,79,22,639,76,0,125,0,181,...,0,40,16,387,0,0,4497,345,0,3.22e+05
WY_Lander,58,0,30,15,209,23,0,68,0,123,...,0,3,3,65,2,0,3707,72,0,1.55e+05
WY_Laramie,295,11,118,10,610,86,0,252,0,256,...,0,33,16,353,27,0,7492,374,0,4.23e+05
WY_Rawlins,123,1,36,5,233,25,0,203,0,172,...,0,8,7,69,2,0,3876,190,0,2.17e+05

In [174]:
transposed_df_sorted = transposed_df_sorted.div(transposed_df_sorted['total_word_count'], axis=0)

# Drop the 'total_wor_count' column if you no longer need it
transposed_df_sorted = transposed_df_sorted.drop(columns=['total_word_count'])
df=transposed_df_sorted
df

,access,allocate,allow,allowable,application,approve,approved,authorize,ban,board,...,require,required,reserve,restrict,review,rezoning,set aside,shall,special,up to
Words,,,,,,,,,,,,,,,,,,,,,
AK_Anchorage,5.90e-04,3.42e-05,2.58e-04,4.85e-05,1.35e-03,1.55e-04,0.00e+00,7.08e-04,1.59e-06,1.38e-03,...,4.26e-03,0.00e+00,1.70e-04,4.13e-05,8.49e-04,5.33e-05,0.00e+00,1.52e-02,6.26e-04,0.00e+00
AK_Homer,5.97e-04,6.40e-05,1.96e-04,8.53e-06,1.37e-03,1.36e-04,0.00e+00,8.44e-04,0.00e+00,1.35e-03,...,4.27e-03,0.00e+00,2.22e-04,3.84e-05,5.97e-04,1.28e-05,0.00e+00,1.56e-02,7.97e-04,0.00e+00
AK_Kenai,4.51e-04,2.88e-05,1.70e-04,3.60e-05,1.41e-03,1.65e-04,0.00e+00,1.61e-03,0.00e+00,2.08e-03,...,3.08e-03,0.00e+00,7.91e-05,9.59e-06,4.17e-04,1.68e-05,0.00e+00,1.25e-02,9.75e-04,0.00e+00
AK_Palmer,4.11e-04,3.89e-05,1.64e-04,2.16e-05,1.05e-03,8.21e-05,0.00e+00,7.65e-04,4.32e-06,9.25e-04,...,3.90e-03,0.00e+00,8.64e-05,2.59e-05,4.36e-04,3.02e-05,0.00e+00,1.61e-02,9.20e-04,0.00e+00
AK_Petersburg,6.25e-04,1.20e-05,2.04e-04,6.01e-05,1.65e-03,1.56e-04,0.00e+00,4.81e-04,3.61e-05,2.40e-03,...,4.03e-03,0.00e+00,1.56e-04,1.20e-05,4.33e-04,3.61e-05,0.00e+00,1.55e-02,5.77e-04,0.00e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WY_Douglas,4.99e-04,6.40e-06,2.21e-04,6.40e-06,2.97e-03,1.28e-04,0.00e+00,9.15e-04,0.00e+00,4.06e-04,...,6.12e-03,0.00e+00,1.18e-04,1.92e-05,1.91e-03,5.56e-04,0.00e+00,1.77e-02,8.25e-04,0.00e+00
WY_Jackson,5.69e-04,4.66e-05,2.46e-04,6.84e-05,1.99e-03,2.36e-04,0.00e+00,3.89e-04,0.00e+00,5.63e-04,...,4.99e-03,0.00e+00,1.24e-04,4.97e-05,1.20e-03,0.00e+00,0.00e+00,1.40e-02,1.07e-03,0.00e+00
WY_Lander,3.74e-04,0.00e+00,1.93e-04,9.67e-05,1.35e-03,1.48e-04,0.00e+00,4.38e-04,0.00e+00,7.93e-04,...,4.74e-03,0.00e+00,1.93e-05,1.93e-05,4.19e-04,1.29e-05,0.00e+00,2.39e-02,4.64e-04,0.00e+00
WY_Laramie,6.98e-04,2.60e-05,2.79e-04,2.36e-05,1.44e-03,2.03e-04,0.00e+00,5.96e-04,0.00e+00,6.05e-04,...,4.41e-03,0.00e+00,7.80e-05,3.78e-05,8.35e-04,6.39e-05,0.00e+00,1.77e-02,8.84e-04,0.00e+00
WY_Rawlins,5.66e-04,4.60e-06,1.66e-04,2.30e-05,1.07e-03,1.15e-04,0.00e+00,9.33e-04,0.00e+00,7.91e-04,...,4.03e-03,0.00e+00,3.68e-05,3.22e-05,3.17e-04,9.20e-06,0.00e+00,1.78e-02,8.74e-04,0.00e+00

In [175]:


# Set the display option for float format to scientific notation
pd.options.display.float_format = '{:.2e}'.format

df

,access,allocate,allow,allowable,application,approve,approved,authorize,ban,board,...,require,required,reserve,restrict,review,rezoning,set aside,shall,special,up to
Words,,,,,,,,,,,,,,,,,,,,,
AK_Anchorage,5.90e-04,3.42e-05,2.58e-04,4.85e-05,1.35e-03,1.55e-04,0.00e+00,7.08e-04,1.59e-06,1.38e-03,...,4.26e-03,0.00e+00,1.70e-04,4.13e-05,8.49e-04,5.33e-05,0.00e+00,1.52e-02,6.26e-04,0.00e+00
AK_Homer,5.97e-04,6.40e-05,1.96e-04,8.53e-06,1.37e-03,1.36e-04,0.00e+00,8.44e-04,0.00e+00,1.35e-03,...,4.27e-03,0.00e+00,2.22e-04,3.84e-05,5.97e-04,1.28e-05,0.00e+00,1.56e-02,7.97e-04,0.00e+00
AK_Kenai,4.51e-04,2.88e-05,1.70e-04,3.60e-05,1.41e-03,1.65e-04,0.00e+00,1.61e-03,0.00e+00,2.08e-03,...,3.08e-03,0.00e+00,7.91e-05,9.59e-06,4.17e-04,1.68e-05,0.00e+00,1.25e-02,9.75e-04,0.00e+00
AK_Palmer,4.11e-04,3.89e-05,1.64e-04,2.16e-05,1.05e-03,8.21e-05,0.00e+00,7.65e-04,4.32e-06,9.25e-04,...,3.90e-03,0.00e+00,8.64e-05,2.59e-05,4.36e-04,3.02e-05,0.00e+00,1.61e-02,9.20e-04,0.00e+00
AK_Petersburg,6.25e-04,1.20e-05,2.04e-04,6.01e-05,1.65e-03,1.56e-04,0.00e+00,4.81e-04,3.61e-05,2.40e-03,...,4.03e-03,0.00e+00,1.56e-04,1.20e-05,4.33e-04,3.61e-05,0.00e+00,1.55e-02,5.77e-04,0.00e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WY_Douglas,4.99e-04,6.40e-06,2.21e-04,6.40e-06,2.97e-03,1.28e-04,0.00e+00,9.15e-04,0.00e+00,4.06e-04,...,6.12e-03,0.00e+00,1.18e-04,1.92e-05,1.91e-03,5.56e-04,0.00e+00,1.77e-02,8.25e-04,0.00e+00
WY_Jackson,5.69e-04,4.66e-05,2.46e-04,6.84e-05,1.99e-03,2.36e-04,0.00e+00,3.89e-04,0.00e+00,5.63e-04,...,4.99e-03,0.00e+00,1.24e-04,4.97e-05,1.20e-03,0.00e+00,0.00e+00,1.40e-02,1.07e-03,0.00e+00
WY_Lander,3.74e-04,0.00e+00,1.93e-04,9.67e-05,1.35e-03,1.48e-04,0.00e+00,4.38e-04,0.00e+00,7.93e-04,...,4.74e-03,0.00e+00,1.93e-05,1.93e-05,4.19e-04,1.29e-05,0.00e+00,2.39e-02,4.64e-04,0.00e+00
WY_Laramie,6.98e-04,2.60e-05,2.79e-04,2.36e-05,1.44e-03,2.03e-04,0.00e+00,5.96e-04,0.00e+00,6.05e-04,...,4.41e-03,0.00e+00,7.80e-05,3.78e-05,8.35e-04,6.39e-05,0.00e+00,1.77e-02,8.84e-04,0.00e+00
WY_Rawlins,5.66e-04,4.60e-06,1.66e-04,2.30e-05,1.07e-03,1.15e-04,0.00e+00,9.33e-04,0.00e+00,7.91e-04,...,4.03e-03,0.00e+00,3.68e-05,3.22e-05,3.17e-04,9.20e-06,0.00e+00,1.78e-02,8.74e-04,0.00e+00

In [176]:

import numpy as np

# Assuming df is already loaded
sd=6
def find_outliers_and_replace(df,sd):
    for column in df.columns:
        mean = df[column].mean()
        std_dev = df[column].std()
        lower_bound = mean - sd * std_dev
        upper_bound = mean + sd * std_dev
        
        # Identify outliers
        outliers = (df[column] > upper_bound)
        
        # Replace non-outliers with NaN
        df[column] = df[column].where(outliers, np.nan)
    
    return df

# Apply the function to the DataFrame
#df = find_outliers_and_replace(df,sd=sd)
df_cleaned=df

In [177]:

# import numpy as np


# def find_outliers_and_replace(df):
#     overall_mean = df.values.mean()
#     overall_std_dev = df.values.std()
#     lower_bound = overall_mean - 3 * overall_std_dev
#     upper_bound = overall_mean + 3 * overall_std_dev
    
#     # Identify outliers
#     outliers = (df < lower_bound) | (df > upper_bound)
    
#     # Replace non-outliers with NaN
#     df = df.where(outliers, np.nan)
    
#     return df

# # Apply the function to the DataFrame
# df = find_outliers_and_replace(df)
# df

In [178]:
#df_cleaned = df.dropna(how='all')
df_cleaned

,access,allocate,allow,allowable,application,approve,approved,authorize,ban,board,...,require,required,reserve,restrict,review,rezoning,set aside,shall,special,up to
Words,,,,,,,,,,,,,,,,,,,,,
AK_Anchorage,5.90e-04,3.42e-05,2.58e-04,4.85e-05,1.35e-03,1.55e-04,0.00e+00,7.08e-04,1.59e-06,1.38e-03,...,4.26e-03,0.00e+00,1.70e-04,4.13e-05,8.49e-04,5.33e-05,0.00e+00,1.52e-02,6.26e-04,0.00e+00
AK_Homer,5.97e-04,6.40e-05,1.96e-04,8.53e-06,1.37e-03,1.36e-04,0.00e+00,8.44e-04,0.00e+00,1.35e-03,...,4.27e-03,0.00e+00,2.22e-04,3.84e-05,5.97e-04,1.28e-05,0.00e+00,1.56e-02,7.97e-04,0.00e+00
AK_Kenai,4.51e-04,2.88e-05,1.70e-04,3.60e-05,1.41e-03,1.65e-04,0.00e+00,1.61e-03,0.00e+00,2.08e-03,...,3.08e-03,0.00e+00,7.91e-05,9.59e-06,4.17e-04,1.68e-05,0.00e+00,1.25e-02,9.75e-04,0.00e+00
AK_Palmer,4.11e-04,3.89e-05,1.64e-04,2.16e-05,1.05e-03,8.21e-05,0.00e+00,7.65e-04,4.32e-06,9.25e-04,...,3.90e-03,0.00e+00,8.64e-05,2.59e-05,4.36e-04,3.02e-05,0.00e+00,1.61e-02,9.20e-04,0.00e+00
AK_Petersburg,6.25e-04,1.20e-05,2.04e-04,6.01e-05,1.65e-03,1.56e-04,0.00e+00,4.81e-04,3.61e-05,2.40e-03,...,4.03e-03,0.00e+00,1.56e-04,1.20e-05,4.33e-04,3.61e-05,0.00e+00,1.55e-02,5.77e-04,0.00e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WY_Douglas,4.99e-04,6.40e-06,2.21e-04,6.40e-06,2.97e-03,1.28e-04,0.00e+00,9.15e-04,0.00e+00,4.06e-04,...,6.12e-03,0.00e+00,1.18e-04,1.92e-05,1.91e-03,5.56e-04,0.00e+00,1.77e-02,8.25e-04,0.00e+00
WY_Jackson,5.69e-04,4.66e-05,2.46e-04,6.84e-05,1.99e-03,2.36e-04,0.00e+00,3.89e-04,0.00e+00,5.63e-04,...,4.99e-03,0.00e+00,1.24e-04,4.97e-05,1.20e-03,0.00e+00,0.00e+00,1.40e-02,1.07e-03,0.00e+00
WY_Lander,3.74e-04,0.00e+00,1.93e-04,9.67e-05,1.35e-03,1.48e-04,0.00e+00,4.38e-04,0.00e+00,7.93e-04,...,4.74e-03,0.00e+00,1.93e-05,1.93e-05,4.19e-04,1.29e-05,0.00e+00,2.39e-02,4.64e-04,0.00e+00
WY_Laramie,6.98e-04,2.60e-05,2.79e-04,2.36e-05,1.44e-03,2.03e-04,0.00e+00,5.96e-04,0.00e+00,6.05e-04,...,4.41e-03,0.00e+00,7.80e-05,3.78e-05,8.35e-04,6.39e-05,0.00e+00,1.77e-02,8.84e-04,0.00e+00
WY_Rawlins,5.66e-04,4.60e-06,1.66e-04,2.30e-05,1.07e-03,1.15e-04,0.00e+00,9.33e-04,0.00e+00,7.91e-04,...,4.03e-03,0.00e+00,3.68e-05,3.22e-05,3.17e-04,9.20e-06,0.00e+00,1.78e-02,8.74e-04,0.00e+00

In [179]:
# Load the CSV file into a DataFrame
file_path = r"C:\Users\clint\Desktop\September 10\Code\Data\Analytic\location_longlat.csv"
df = pd.read_csv(file_path)
df = df.drop(['restrict_NA_permit', 'restrict_NA_units', 'limit_NA_dwellings', 'limit_NA_dwelling_units'], axis=1)
# Display the DataFrame
df_long_lat=df

In [180]:


# Assuming df_cleaned and df are already defined
df_cleaned = pd.merge(df_cleaned, df, left_on='Words', right_on='muni', how='left')
df_cleaned.set_index('muni', inplace=True)
df_cleaned = df_cleaned.drop(['GEOID', 'statename', 'place'], axis=1)
df_cleaned

,access,allocate,allow,allowable,application,approve,approved,authorize,ban,board,...,reserve,restrict,review,rezoning,set aside,shall,special,up to,INTPTLAT10,INTPTLON10
muni,,,,,,,,,,,,,,,,,,,,,
AK_Anchorage,5.90e-04,3.42e-05,2.58e-04,4.85e-05,1.35e-03,1.55e-04,0.00e+00,7.08e-04,1.59e-06,1.38e-03,...,1.70e-04,4.13e-05,8.49e-04,5.33e-05,0.00e+00,1.52e-02,6.26e-04,0.00e+00,6.12e+01,-1.49e+02
AK_Homer,5.97e-04,6.40e-05,1.96e-04,8.53e-06,1.37e-03,1.36e-04,0.00e+00,8.44e-04,0.00e+00,1.35e-03,...,2.22e-04,3.84e-05,5.97e-04,1.28e-05,0.00e+00,1.56e-02,7.97e-04,0.00e+00,5.96e+01,-1.52e+02
AK_Kenai,4.51e-04,2.88e-05,1.70e-04,3.60e-05,1.41e-03,1.65e-04,0.00e+00,1.61e-03,0.00e+00,2.08e-03,...,7.91e-05,9.59e-06,4.17e-04,1.68e-05,0.00e+00,1.25e-02,9.75e-04,0.00e+00,6.06e+01,-1.51e+02
AK_Palmer,4.11e-04,3.89e-05,1.64e-04,2.16e-05,1.05e-03,8.21e-05,0.00e+00,7.65e-04,4.32e-06,9.25e-04,...,8.64e-05,2.59e-05,4.36e-04,3.02e-05,0.00e+00,1.61e-02,9.20e-04,0.00e+00,6.16e+01,-1.49e+02
AK_Petersburg,6.25e-04,1.20e-05,2.04e-04,6.01e-05,1.65e-03,1.56e-04,0.00e+00,4.81e-04,3.61e-05,2.40e-03,...,1.56e-04,1.20e-05,4.33e-04,3.61e-05,0.00e+00,1.55e-02,5.77e-04,0.00e+00,5.68e+01,-1.33e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WY_Douglas,4.99e-04,6.40e-06,2.21e-04,6.40e-06,2.97e-03,1.28e-04,0.00e+00,9.15e-04,0.00e+00,4.06e-04,...,1.18e-04,1.92e-05,1.91e-03,5.56e-04,0.00e+00,1.77e-02,8.25e-04,0.00e+00,4.28e+01,-1.05e+02
WY_Jackson,5.69e-04,4.66e-05,2.46e-04,6.84e-05,1.99e-03,2.36e-04,0.00e+00,3.89e-04,0.00e+00,5.63e-04,...,1.24e-04,4.97e-05,1.20e-03,0.00e+00,0.00e+00,1.40e-02,1.07e-03,0.00e+00,4.35e+01,-1.11e+02
WY_Lander,3.74e-04,0.00e+00,1.93e-04,9.67e-05,1.35e-03,1.48e-04,0.00e+00,4.38e-04,0.00e+00,7.93e-04,...,1.93e-05,1.93e-05,4.19e-04,1.29e-05,0.00e+00,2.39e-02,4.64e-04,0.00e+00,4.28e+01,-1.09e+02
WY_Laramie,6.98e-04,2.60e-05,2.79e-04,2.36e-05,1.44e-03,2.03e-04,0.00e+00,5.96e-04,0.00e+00,6.05e-04,...,7.80e-05,3.78e-05,8.35e-04,6.39e-05,0.00e+00,1.77e-02,8.84e-04,0.00e+00,4.13e+01,-1.06e+02
WY_Rawlins,5.66e-04,4.60e-06,1.66e-04,2.30e-05,1.07e-03,1.15e-04,0.00e+00,9.33e-04,0.00e+00,7.91e-04,...,3.68e-05,3.22e-05,3.17e-04,9.20e-06,0.00e+00,1.78e-02,8.74e-04,0.00e+00,4.18e+01,-1.07e+02

In [181]:
df_cleaned = df_cleaned.nsmallest(5, "shall")
df_cleaned

,access,allocate,allow,allowable,application,approve,approved,authorize,ban,board,...,reserve,restrict,review,rezoning,set aside,shall,special,up to,INTPTLAT10,INTPTLON10
muni,,,,,,,,,,,,,,,,,,,,,
IN_Richmond,3.27e-03,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,5.85e-03,0.00e+00,3.98e+01,-8.49e+01
MN_Minnetonka,6.45e-04,0.00e+00,3.74e-04,3.15e-05,1.38e-03,1.14e-04,0.00e+00,6.53e-04,3.93e-06,2.79e-04,...,4.33e-05,7.87e-06,6.73e-04,1.22e-04,0.00e+00,2.74e-03,4.29e-04,0.00e+00,4.49e+01,-9.35e+01
IN_Corydon,1.18e-04,0.00e+00,0.00e+00,0.00e+00,4.73e-04,0.00e+00,0.00e+00,2.36e-04,1.18e-04,2.36e-03,...,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,4.26e-03,3.55e-04,0.00e+00,3.82e+01,-8.61e+01
MN_StCloud,5.09e-04,5.47e-06,2.52e-04,4.65e-05,2.34e-03,1.78e-04,0.00e+00,6.13e-04,1.09e-05,8.21e-04,...,7.39e-05,1.64e-05,6.18e-04,8.48e-05,0.00e+00,4.52e-03,6.81e-04,0.00e+00,4.55e+01,-9.42e+01
MN_BrooklynPark,4.89e-04,1.03e-05,3.22e-04,4.45e-05,1.41e-03,9.58e-05,0.00e+00,6.26e-04,1.37e-05,3.28e-04,...,1.61e-04,1.71e-05,6.74e-04,1.71e-05,0.00e+00,4.81e-03,4.24e-04,0.00e+00,4.51e+01,-9.33e+01

In [182]:
df_cleaned = df_cleaned.dropna(subset=['INTPTLAT10'])

In [183]:
# df_cleaned = df_cleaned[df_cleaned["shall"] == 0]
# df_cleaned

In [184]:
df_long_lat=df_long_lat.dropna()
df_long_lat

      INTPTLAT10  INTPTLON10    GEOID statename       place           muni
0       6.12e+01   -1.49e+02   203000        AK   Anchorage   AK_Anchorage
1       5.96e+01   -1.52e+02   233140        AK       Homer       AK_Homer
2       6.06e+01   -1.51e+02   238420        AK       Kenai       AK_Kenai
3       6.16e+01   -1.49e+02   258660        AK      Palmer      AK_Palmer
4       5.68e+01   -1.33e+02   260310        AK  Petersburg  AK_Petersburg
...          ...         ...      ...       ...         ...            ...
2634    4.28e+01   -1.05e+02  5621125        WY     Douglas     WY_Douglas
2635    4.35e+01   -1.11e+02  5640120        WY     Jackson     WY_Jackson
2636    4.28e+01   -1.09e+02  5644760        WY      Lander      WY_Lander
2637    4.13e+01   -1.06e+02  5645050        WY     Laramie     WY_Laramie
2638    4.18e+01   -1.07e+02  5663900        WY     Rawlins     WY_Rawlins

[2375 rows x 6 columns]

In [185]:
import pandas as pd
import folium
from folium import IFrame

# Assuming df_cleaned is already loaded
# Example: df_cleaned = pd.read_csv('path_to_your_file.csv')

# Filter to only include the "shall" column
column_name = "shall"

# Initialize a map centered on the US
us_map = folium.Map(location=[37.0902, -95.7129], zoom_start=4)

# Add a title to the map
title_html = f'''
             <h3 align="center" style="font-size:20px"><b>Places that dont/minimally use "{column_name}"</b></h3>
             '''
us_map.get_root().html.add_child(folium.Element(title_html))

# Gives you the general dataset
for _, row in df_long_lat.iterrows():
    folium.CircleMarker(
        location=[row['INTPTLAT10'], row['INTPTLON10']],
        radius=5,
        color='red',
        fill=True,
        fill_color='red'
    ).add_to(us_map)

# Iterate through the "shall" column to find non-NaN values
for index, value in df_cleaned[column_name].dropna().items():
    # Get the latitude and longitude
    lat = df_cleaned.at[index, 'INTPTLAT10']
    lon = df_cleaned.at[index, 'INTPTLON10']
    
    # Create a popup with the index name, column name, and value
    popup_content = f"Index: {index}<br>Column: {column_name}<br>Value: {value}"
    popup = folium.Popup(IFrame(popup_content, width=200, height=100))
    
    # Add a marker to the map
    folium.Marker(location=[lat, lon], popup=popup).add_to(us_map)

# Save the map to an HTML file with the column name
us_map.save(f'us_map_{column_name}_lowest.html')